name: Awesome List Dead Links (daily check)  # Name of the workflow

on:
  schedule:
    - cron: '0 */24 * * *' # Schedule the workflow to run every 24 hours
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  linkChecker:
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner
    steps:
      - name: Checkout repository  # Step to checkout the repository
        uses: actions/checkout@v4  # Use the checkout action version 4
      - name: Run lychee link checker  # Step to run the lychee link checker
        uses: lycheeverse/lychee-action@v1.10.0  # Use the lychee action version 1.10.0
        with:
          args: --verbose --no-progress --exclude-mail --timeout 20 README.md  # Arguments for the lychee link checker
      - name: Upload link checker report  # Step to upload the link checker report
        uses: actions/upload-artifact@v4  # Use the upload artifact action version 4
        with:
          name: lychee-report  # Name of the artifact
          path: ./lychee/report.md  # Path to the report file
